/* eslint-disable */
/**
 * Generates src/version.ts from package.json.
 *
 * Why this exists: the extension reports its version to the API gateway in the
 * `X-Smarts-Client` header, and tsconfig sets `rootDir: "src"` — so we cannot simply
 * `import { version } from '../package.json'` (TS6059: file outside rootDir).
 *
 * Hand-copying the version instead would drift silently on the next release: the header
 * would keep reporting a stale version and nothing would fail. Generating it at build time
 * makes package.json the single source of truth.
 *
 * Wired into `build:lib` / `build:lib:prod`. The output is committed so a bare `tsc`
 * (typecheck, editor) works without running this first.
 */
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const { version } = JSON.parse(
  fs.readFileSync(path.join(root, 'package.json'), 'utf8')
);

if (!version) {
  console.error('[sync-version] no "version" in package.json');
  process.exit(1);
}

const out = path.join(root, 'src', 'version.ts');
const contents = `// AUTO-GENERATED by scripts/sync-version.js — do not edit by hand.
// Source of truth is package.json; run \`jlpm build\` to regenerate.
export const VERSION = '${version}';
`;

// Only write when it actually changed, so we don't churn mtimes on every build.
const existing = fs.existsSync(out) ? fs.readFileSync(out, 'utf8') : '';
if (existing !== contents) {
  fs.writeFileSync(out, contents);
  console.log(`[sync-version] src/version.ts -> ${version}`);
}
