// NOTE: Adapted from smarts-bio-vscode/webview-ui/chat/components/MessageBubble.tsx
// Key change: "Insert into Editor ↓" → "Insert as Cell ↓"
import React, { useState, useRef, useEffect } from 'react';
import { marked } from 'marked';
import type { ChatMessage } from '../types';

marked.use({ gfm: true, breaks: true });

interface Props {
  message: ChatMessage;
  isStreaming?: boolean;
  onInsertCode: (code: string) => void;
  onSuggestion: (text: string) => void;
}

export function MessageBubble({
  message,
  isStreaming,
  onInsertCode,
  onSuggestion,
}: Props): React.ReactElement {
  const isUser = message.role === 'user';

  return (
    <div
      style={{
        ...styles.bubble,
        alignSelf: isUser ? 'flex-end' : 'flex-start',
        maxWidth: isUser ? '80%' : '95%',
        background: isUser
          ? 'var(--vscode-button-background)'
          : message.isError
            ? 'var(--vscode-inputValidation-errorBackground)'
            : 'var(--vscode-editor-background)',
        color: isUser ? 'var(--vscode-button-foreground)' : 'var(--vscode-foreground)',
        border: isUser ? 'none' : '1px solid var(--vscode-panel-border)',
      }}
    >
      {isUser ? (
        <span style={styles.userText}>{message.content}</span>
      ) : (
        <AssistantContent
          content={message.content}
          isStreaming={isStreaming}
          onInsertCode={onInsertCode}
          onSuggestion={onSuggestion}
        />
      )}
    </div>
  );
}

function AssistantContent({
  content,
  isStreaming,
  onInsertCode,
  onSuggestion,
}: {
  content: string;
  isStreaming?: boolean;
  onInsertCode: (code: string) => void;
  onSuggestion: (text: string) => void;
}): React.ReactElement {
  const containerRef = useRef<HTMLDivElement>(null);

  // Attach click listener for entity-link spans (generated by processEntityMarkup)
  useEffect(() => {
    const container = containerRef.current;
    if (!container) return;

    const handleClick = (e: MouseEvent) => {
      const target = e.target as HTMLElement;
      if (target.classList.contains('entity-link')) {
        e.preventDefault();
        const raw = target.getAttribute('data-entity');
        if (raw) {
          try {
            const { type, name, context } = JSON.parse(raw);
            onSuggestion(generateFollowUpQuestion(type, name, context));
          } catch {}
        }
      }
    };

    container.addEventListener('click', handleClick);
    return () => container.removeEventListener('click', handleClick);
  }, [onSuggestion]);

  const segments = parseContent(content);

  return (
    <div ref={containerRef} style={styles.assistantContent}>
      {segments.map((seg, i) => {
        if (seg.type === 'code') {
          return (
            <CodeBlock
              key={i}
              code={seg.content}
              language={seg.language ?? ''}
              onInsert={onInsertCode}
            />
          );
        }
        return (
          <div
            key={i}
            className="md"
            dangerouslySetInnerHTML={{ __html: marked.parse(processEntityMarkup(seg.content)) as string }}
          />
        );
      })}
      {isStreaming && <span style={styles.cursor}>▋</span>}

      {!isStreaming && content.includes('→') && (
        <SuggestionChips content={content} onSuggestion={onSuggestion} />
      )}
    </div>
  );
}

/** Convert [ENTITY|type|name|context] markers into clickable spans. */
function processEntityMarkup(text: string): string {
  return text.replace(
    /\[ENTITY\|([^|]+)\|([^|]+)\|([^\]]+)\]/g,
    (_, type, name, context) => {
      const entityData = JSON.stringify({ type, name, context }).replace(/'/g, '&#39;');
      return `<span class="entity-link" data-entity='${entityData}'>${name}</span>`;
    },
  );
}

function generateFollowUpQuestion(type: string, name: string, context: string): string {
  const templates: Record<string, string> = {
    gene: `Tell me more about the ${name} gene, including its function, chromosomal location, and associated diseases`,
    protein: `Provide detailed information about the ${name} protein, including its structure, function, and biological role`,
    compound: `What is ${name}? Explain its chemical properties, biological activity, and therapeutic applications`,
    pathway: `Explain the ${name} pathway, its biological significance, key components, and regulation`,
    uniprot: `Provide more details about UniProt ID ${name}, including its sequence, structure, and function`,
    pdb: `Tell me more about PDB entry ${name}, including its structure, resolution, and experimental method`,
    organism: `Tell me about ${name}, including its taxonomy, characteristics, and research significance`,
    patent: `Summarize this patent: ${name} and provide a link to the full patent`,
    'intellectual-property': `Summarize this patent: ${name} and provide a link to the full patent`,
    smiles: `Tell me more about the molecule ${name}, including its chemical properties and biological activity`,
    sequence: `Analyze this biological sequence: ${name}`,
  };
  return templates[context] ?? templates[type] ?? `Tell me more about ${name} in the context of ${context}`;
}

function CodeBlock({
  code,
  language,
  onInsert,
}: {
  code: string;
  language: string;
  onInsert: (code: string) => void;
}): React.ReactElement {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(code).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  return (
    <div style={styles.codeBlock}>
      <div style={styles.codeHeader}>
        <span style={styles.codeLang}>{language || 'code'}</span>
        <div style={styles.codeActions}>
          <button style={styles.codeBtn} onClick={handleCopy}>
            {copied ? '✓ Copied' : 'Copy'}
          </button>
          <button style={styles.codeBtnPrimary} onClick={() => onInsert(code)}>
            Insert as Cell ↓
          </button>
        </div>
      </div>
      <pre style={styles.codePre}>
        <code>{code}</code>
      </pre>
    </div>
  );
}

function SuggestionChips({
  content,
  onSuggestion,
}: {
  content: string;
  onSuggestion: (text: string) => void;
}): React.ReactElement | null {
  const lines = content.split('\n');
  const suggestions = lines
    .filter(l => l.trim().startsWith('→'))
    .map(l => l.trim().slice(1).trim())
    .filter(Boolean)
    .slice(0, 3);

  if (suggestions.length === 0) {
    return null;
  }

  return (
    <div style={styles.suggestions}>
      <div style={styles.suggestionsLabel}>Suggested next steps:</div>
      {suggestions.map(s => (
        <button key={s} style={styles.suggestionChip} onClick={() => onSuggestion(s)}>
          → {s}
        </button>
      ))}
    </div>
  );
}

interface ContentSegment {
  type: 'text' | 'code';
  content: string;
  language?: string;
}

function parseContent(content: string): ContentSegment[] {
  const segments: ContentSegment[] = [];
  const codeBlockRegex = /```(\w*)\n?([\s\S]*?)```/g;
  let lastIndex = 0;
  let match: RegExpExecArray | null;

  while ((match = codeBlockRegex.exec(content)) !== null) {
    if (match.index > lastIndex) {
      const text = content.slice(lastIndex, match.index).trim();
      if (text) {
        segments.push({ type: 'text', content: text });
      }
    }
    segments.push({ type: 'code', content: match[2].trim(), language: match[1] || undefined });
    lastIndex = match.index + match[0].length;
  }

  const remaining = content.slice(lastIndex).trim();
  if (remaining) {
    segments.push({ type: 'text', content: remaining });
  }

  return segments;
}

const styles: Record<string, React.CSSProperties> = {
  bubble: {
    margin: '4px 12px',
    padding: '8px 10px',
    borderRadius: '8px',
    wordBreak: 'break-word',
  },
  userText: {
    fontSize: '13px',
    whiteSpace: 'pre-wrap',
  },
  assistantContent: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  cursor: {
    animation: 'blink 1s step-end infinite',
  },
  codeBlock: {
    background: 'var(--vscode-textCodeBlock-background)',
    borderRadius: '4px',
    overflow: 'hidden',
    border: '1px solid var(--vscode-panel-border)',
  },
  codeHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '4px 8px',
    borderBottom: '1px solid var(--vscode-panel-border)',
  },
  codeLang: {
    fontSize: '11px',
    color: 'var(--vscode-descriptionForeground)',
    textTransform: 'uppercase',
  },
  codeActions: {
    display: 'flex',
    gap: '6px',
  },
  codeBtn: {
    fontSize: '11px',
    padding: '2px 6px',
    background: 'var(--vscode-button-secondaryBackground)',
    color: 'var(--vscode-button-secondaryForeground)',
    border: 'none',
    borderRadius: '3px',
    cursor: 'pointer',
    fontFamily: 'var(--vscode-font-family)',
  },
  codeBtnPrimary: {
    fontSize: '11px',
    padding: '2px 6px',
    background: 'var(--vscode-button-background)',
    color: 'var(--vscode-button-foreground)',
    border: 'none',
    borderRadius: '3px',
    cursor: 'pointer',
    fontFamily: 'var(--vscode-font-family)',
  },
  codePre: {
    margin: 0,
    padding: '10px 12px',
    overflowX: 'auto',
    fontSize: '12px',
    lineHeight: 1.5,
    fontFamily: 'var(--vscode-editor-font-family, monospace)',
  },
  suggestions: {
    marginTop: '6px',
    paddingTop: '6px',
    borderTop: '1px solid var(--vscode-panel-border)',
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  suggestionsLabel: {
    fontSize: '11px',
    color: 'var(--vscode-descriptionForeground)',
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
    marginBottom: '2px',
  },
  suggestionChip: {
    padding: '4px 8px',
    textAlign: 'left',
    background: 'transparent',
    color: 'var(--vscode-textLink-foreground)',
    border: '1px solid var(--vscode-panel-border)',
    borderRadius: '3px',
    fontSize: '12px',
    cursor: 'pointer',
    fontFamily: 'var(--vscode-font-family)',
  },
};
